#!/usr/bin/env php
<?php

/*
* This file is part of the raven package.
*
* (c) Amin Alizade <motammem@gmail.com>
*
* For the full copyright and license information, please view the LICENSE
* file that was distributed with this source code.
*/

require_once __DIR__ . '/vendor/autoload.php';

$application = new \Symfony\Component\Console\Application();
$application->add(new \Raven\Core\Command\RavenCommand());
$application->run();
