#!/usr/bin/env php
<?php

/*
* This file is part of the raven package.
*
* (c) Amin Alizade <motammem@gmail.com>
*
* For the full copyright and license information, please view the LICENSE
* file that was distributed with this source code.
*/

require_once __DIR__ . '/bootstrap.php';
$application = new \Symfony\Component\Console\Application();
$application->setCatchExceptions(false);

$application->add(new \Raven\Core\Command\RavenCommand());

try {

    $application->run();
} catch (\Raven\Core\Exception\CrawlerException $e) {
    global $logger;
    $logger->alert($e->getMessage(), $e->getContext());
}
